import {MigrationInterface, QueryRunner} from "typeorm";

export class Migration1613638790024 implements MigrationInterface {
    name = 'Migration1613638790024'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `chat_member` (`userUuid` varchar(255) NOT NULL, `chatUuid` varchar(255) NOT NULL, `joinedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `role` int NOT NULL DEFAULT '2', UNIQUE INDEX `compound` (`userUuid`, `chatUuid`), PRIMARY KEY (`userUuid`, `chatUuid`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `joinedAt`");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `role`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `promotedAt`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `permissions`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `promotedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `permissions` int NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `joinedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `role` int NOT NULL DEFAULT '2'");
        await queryRunner.query("ALTER TABLE `blacklist_token` CHANGE `expires` `expires` timestamp NOT NULL");
        await queryRunner.query("ALTER TABLE `message` CHANGE `chatUuid` `chatUuid` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `message` CHANGE `senderUuid` `senderUuid` varchar(36) NULL");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `name` `name` text NULL");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `tag` `tag` text NULL");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `description` `description` text NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `userUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `chatUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `pending_user` CHANGE `expires` `expires` timestamp NOT NULL");
        await queryRunner.query("DROP INDEX `compound` ON `chat_member`");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `userUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `chatUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `chatUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `userUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("CREATE UNIQUE INDEX `compound` ON `chat_admin` (`userUuid`, `chatUuid`)");
        await queryRunner.query("CREATE UNIQUE INDEX `compound` ON `chat_member` (`userUuid`, `chatUuid`)");
        await queryRunner.query("CREATE INDEX `IDX_7945d28d11224831fa9b6ed593` ON `chat_member` (`userUuid`)");
        await queryRunner.query("CREATE INDEX `IDX_16449b4a6890a318c732fc7b85` ON `chat_member` (`chatUuid`)");
        await queryRunner.query("CREATE INDEX `IDX_eb2304cda76dfffef95cef3af0` ON `chat_admin` (`chatUuid`)");
        await queryRunner.query("CREATE INDEX `IDX_e3c18c6334be1c65c35e536455` ON `chat_admin` (`userUuid`)");
        await queryRunner.query("ALTER TABLE `message` ADD CONSTRAINT `FK_828afc5242eb3dcc6e40a21f450` FOREIGN KEY (`chatUuid`) REFERENCES `chat`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message` ADD CONSTRAINT `FK_290972857b626d64f9e4266a9e4` FOREIGN KEY (`senderUuid`) REFERENCES `user`(`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `chat_member` ADD CONSTRAINT `FK_7945d28d11224831fa9b6ed5935` FOREIGN KEY (`userUuid`) REFERENCES `user`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `chat_member` ADD CONSTRAINT `FK_16449b4a6890a318c732fc7b851` FOREIGN KEY (`chatUuid`) REFERENCES `chat`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD CONSTRAINT `FK_eb2304cda76dfffef95cef3af00` FOREIGN KEY (`chatUuid`) REFERENCES `chat`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD CONSTRAINT `FK_e3c18c6334be1c65c35e5364553` FOREIGN KEY (`userUuid`) REFERENCES `user`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `chat_admin` DROP FOREIGN KEY `FK_e3c18c6334be1c65c35e5364553`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP FOREIGN KEY `FK_eb2304cda76dfffef95cef3af00`");
        await queryRunner.query("ALTER TABLE `chat_member` DROP FOREIGN KEY `FK_16449b4a6890a318c732fc7b851`");
        await queryRunner.query("ALTER TABLE `chat_member` DROP FOREIGN KEY `FK_7945d28d11224831fa9b6ed5935`");
        await queryRunner.query("ALTER TABLE `message` DROP FOREIGN KEY `FK_290972857b626d64f9e4266a9e4`");
        await queryRunner.query("ALTER TABLE `message` DROP FOREIGN KEY `FK_828afc5242eb3dcc6e40a21f450`");
        await queryRunner.query("DROP INDEX `IDX_e3c18c6334be1c65c35e536455` ON `chat_admin`");
        await queryRunner.query("DROP INDEX `IDX_eb2304cda76dfffef95cef3af0` ON `chat_admin`");
        await queryRunner.query("DROP INDEX `IDX_16449b4a6890a318c732fc7b85` ON `chat_member`");
        await queryRunner.query("DROP INDEX `IDX_7945d28d11224831fa9b6ed593` ON `chat_member`");
        await queryRunner.query("DROP INDEX `compound` ON `chat_member`");
        await queryRunner.query("DROP INDEX `compound` ON `chat_admin`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `userUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `chatUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `chatUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `userUuid` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_member` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_member` ADD PRIMARY KEY (`userUuid`, `chatUuid`)");
        await queryRunner.query("CREATE UNIQUE INDEX `compound` ON `chat_member` (`userUuid`, `chatUuid`)");
        await queryRunner.query("ALTER TABLE `pending_user` CHANGE `expires` `expires` timestamp NOT NULL DEFAULT ''0000-00-00 00:00:00''");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `chatUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `chatUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`)");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `userUuid`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `userUuid` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD PRIMARY KEY (`chatUuid`, `userUuid`)");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `description` `description` text NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `tag` `tag` text NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `chat` CHANGE `name` `name` text NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `message` CHANGE `senderUuid` `senderUuid` varchar(36) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `message` CHANGE `chatUuid` `chatUuid` varchar(36) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `blacklist_token` CHANGE `expires` `expires` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `role`");
        await queryRunner.query("ALTER TABLE `chat_member` DROP COLUMN `joinedAt`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `permissions`");
        await queryRunner.query("ALTER TABLE `chat_admin` DROP COLUMN `promotedAt`");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `permissions` int NOT NULL");
        await queryRunner.query("ALTER TABLE `chat_admin` ADD `promotedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `role` int NOT NULL DEFAULT '2'");
        await queryRunner.query("ALTER TABLE `chat_member` ADD `joinedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("DROP INDEX `compound` ON `chat_member`");
        await queryRunner.query("DROP TABLE `chat_member`");
    }

}
